spring:
   datasource:
      url: jdbc:mysql://192.168.28.130:3306/gzz?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: gzz
      password: gzz
#自定义配置
   rootpath: ${ROOT_PATH:D:/nginx/html/} ##${}兼容docker
   rooturl: http://${ROOT_URL:localhost}/