server:
   port: 9999
   compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
spring: 
   mvc.pathmatch.matching-strategy: ant_path_matcher #解决swagger3.0.0启动报错
   profiles:
      active: prod
   servlet.multipart.max-file-size: 5MB #单文件上传大小
   servlet.multipart.max-request-size: 10MB #总文件上传大小
   application:
      name: spring-boot
   flyway:
      enabled: true    # 如果启动的时候需要flyway管理sql脚本的话，将enabled设置为true
      baseline-on-migrate: true # 如果数据库不是空表，需要设置成 true，否则启动报错
      clean-on-validation-error: false # 验证错误时 是否自动清除数据库 高危操作!

#LandWellApi请求url前缀   测试用
sys:
   urlPre: http://www.keybox21.com:9505/api/